sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
install: yarn install
jobs:
  include:
    - stage: Build and test
      script:
        - yarn validate
        - yarn test
        - yarn build
    - stage: npm release
      script: yarn build
      deploy:
        provider: npm
        email: $YOUR_EMAIL_ADDESS
        api_key: $YOUR_AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
after_success: kcd-scripts travis-after-success
branches:
  only:
    - master
    - /^v[0-9]+.*$/
